#!/bin/bash
DEBIAN_FRONTEND=noninteractive apt install unzip wget curl sudo -y &>/dev/null
wget -O ngrok-stable-linux-amd64.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip &>/dev/null && unzip -o ngrok-stable-linux-amd64.zip &>/dev/null
clear
./ngrok authtoken $TOKEN 
nohup ./ngrok tcp 5900 &>/dev/null &
echo "Downloading QEMU"
DEBIAN_FRONTEND=noninteractive apt install -y qemu-kvm &>/dev/null
echo Download Lite
[ -s HaiDang5090.qcow2 ] || sudo wget -O HaiDang5090.qcow2 https://app.vagrantup.com/TinCowBoy/boxes/NexusLitOS10LTSC/versions/1.0/providers/qemu.box &>/dev/null
disk=$(df -h /tmp | tail -1 | awk '{print $4}')
qemu-img resize HaiDang5090.qcow2 $disk
availableRAMcommand="free -m | tail -2 | head -1 | awk '{print \$7}'"
availableRAM=$(echo $availableRAMcommand | bash)
custom_param_ram="-m "$(expr $availableRAM / 2 )"M"
cpus=$(lscpu | grep CPU\(s\) | head -1 | cut -f2 -d":" | awk '{$1=$1;print}')
custom_param_cpu=$(expr $cpus / 2 )
echo "QEMU-KVM Windows 11 by fb.com/thuong.hai.581"
echo "$custom_param_cpu / $custom_param_ram"
echo Your RDP IP Address:
curl --silent --show-error http://127.0.0.1:4040/api/tunnels | sed -nE 's/.*public_url":"tcp:..([^"]*).*/\1/p'
echo User: Administrator
echo Password: Thuonghai001
echo Script by fb.com/thuong.hai.581
echo Wait 1-2m VM boot up before connect. 
sudo qemu-system-x86_64 -nographic -net nic -net user -vnc :0 -show-cursor $custom_param_ram -enable-kvm -cpu host,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time,+nx -M pc -smp cores=$custom_param_cpu -vga std -machine type=pc,accel=kvm -usb -device usb-tablet -k en-us -drive file=HaiDang5090.qcow2,index=0,media=disk,format=qcow2 -boot once=d
